"""Simplified zebrafish larva body for swimming simulation.

Models undulatory swimming: alternating left-right muscle contractions
propagating along the body produce a sinusoidal wave. No MuJoCo
dependency -- uses simple 2D physics for maximum performance and
portability.

Physics model:
- The fish body is a chain of N rigid segments connected by joints.
- Each joint has left/right muscle actuators that control the angle.
- Thrust is generated by the lateral force component of each segment
  as it sweeps through the water (resistive force theory).
- Drag is anisotropic: higher in the normal direction than tangential,
  which is what makes undulatory swimming work.

Reference:
- Lighthill 1971: Large-amplitude elongated-body theory of fish locomotion
- McHenry & Lauder 2005: Mechanical scaling of zebrafish swimming
- Muller & van Leeuwen 2004: Swimming of larval zebrafish
"""

from __future__ import annotations

import logging
import math

import numpy as np

from creatures.body.base import BodyConfig, BodyModel, BodyState

logger = logging.getLogger(__name__)

# Default body configuration
# We use normalized units for numerical stability:
# length unit = 1 body length, mass unit = 1 body mass, time unit = seconds
N_SEGMENTS = 20  # number of body segments
SEGMENT_LENGTH = 1.0 / N_SEGMENTS  # normalized: total body = 1.0
BODY_MASS = 1.0  # normalized mass
BODY_LENGTH = 1.0  # normalized total length

# Drag coefficients (resistive force theory)
# Normal drag >> tangential drag for undulatory propulsion
C_TANGENTIAL = 2.0  # tangential drag coefficient
C_NORMAL = 8.0  # normal drag coefficient (4x tangential, per RFT)

# Joint stiffness and damping
JOINT_STIFFNESS = 5.0  # passive stiffness restoring to straight
JOINT_DAMPING = 2.0  # viscous damping at joints
JOINT_RANGE = math.radians(30)  # max joint angle (~30 degrees)

# Motor scaling
MUSCLE_TORQUE_SCALE = 10.0  # muscle activation -> torque


class FishBody(BodyModel):
    """Simplified zebrafish larva body for swimming simulation.

    Models undulatory swimming: alternating left-right muscle contractions
    propagating along the body produce a sinusoidal wave.

    No MuJoCo dependency -- uses simple 2D physics for maximum performance.
    The model uses resistive force theory (RFT) for hydrodynamics, which
    is appropriate for the low Reynolds number regime of larval zebrafish.
    """

    def __init__(
        self,
        config: BodyConfig | None = None,
        n_segments: int = N_SEGMENTS,
    ) -> None:
        self._config = config or BodyConfig(dt=1.0)
        self.n_segments = n_segments
        self.n_joints = n_segments - 1

        # State variables
        self.segment_angles = np.zeros(self.n_joints)  # joint angles (rad)
        self.segment_angular_vel = np.zeros(self.n_joints)  # angular velocity
        self.position = np.array([0.0, 0.0])  # center of mass (2D)
        self.heading = 0.0  # body heading (radians, 0 = +x)
        self.velocity = np.array([0.0, 0.0])  # COM velocity
        self.angular_velocity = 0.0  # body rotation rate

        # External forces pending application
        self._external_forces: dict[str, tuple[float, float, float]] = {}

        # Precompute segment properties
        self._seg_length = SEGMENT_LENGTH
        self._seg_mass = BODY_MASS / n_segments

        logger.info(
            f"FishBody: {n_segments} segments, "
            f"{self.n_joints} joints, "
            f"total length {n_segments * SEGMENT_LENGTH * 1000:.1f}mm"
        )

    def reset(self) -> BodyState:
        """Reset body to initial straight position at origin."""
        self.segment_angles[:] = 0.0
        self.segment_angular_vel[:] = 0.0
        self.position[:] = 0.0
        self.heading = 0.0
        self.velocity[:] = 0.0
        self.angular_velocity = 0.0
        self._external_forces.clear()
        return self.get_state()

    def get_sensory_input(self) -> dict[str, float]:
        """Return sensor readings mapped to neuron IDs.

        For zebrafish, we provide:
        - Lateral line sensors (water flow detection along body)
        - Proprioceptive feedback (joint angles)
        """
        result: dict[str, float] = {}
        gain = self._config.sensor_gain

        # Lateral line: sense water flow (velocity-dependent)
        speed = float(np.linalg.norm(self.velocity))
        # Sensory neurons AUD_0..AUD_9 map to lateral line
        for i in range(min(10, self.n_segments)):
            # Flow sensor proportional to speed and segment curvature
            curvature = 0.0
            if i < self.n_joints:
                curvature = abs(self.segment_angles[i])
            sensor_val = (speed * 1000 + curvature * 10) * gain
            if sensor_val > 0.001:
                result[f"AUD_{i}"] = sensor_val

        return result

    def _compute_segment_positions(self) -> list[tuple[float, float]]:
        """Compute 2D positions of each segment center from joint angles."""
        positions = []
        # Start from head
        x, y = self.position[0], self.position[1]
        angle = self.heading

        for i in range(self.n_segments):
            # Segment center
            cx = x + (self._seg_length / 2) * math.cos(angle)
            cy = y + (self._seg_length / 2) * math.sin(angle)
            positions.append((cx, cy))

            # Move to next joint
            x += self._seg_length * math.cos(angle)
            y += self._seg_length * math.sin(angle)

            # Apply joint angle
            if i < self.n_joints:
                angle += self.segment_angles[i]

        return positions

    def step(self, muscle_activations: dict[str, float]) -> BodyState:
        """Step physics with given muscle activations.

        Args:
            muscle_activations: Dict mapping actuator names to activation values.
                Actuator names: "left_0" .. "left_N" and "right_0" .. "right_N"
                for left/right muscles at each joint. Values in [-1, 1].

        Returns:
            Updated body state.
        """
        dt = self._config.dt / 1000.0  # ms -> seconds
        motor_gain = self._config.motor_gain

        # Convert muscle activations to joint torques
        joint_torques = np.zeros(self.n_joints)
        for name, activation in muscle_activations.items():
            parts = name.split("_")
            if len(parts) != 2:
                continue
            side, idx_str = parts
            try:
                idx = int(idx_str)
            except ValueError:
                continue
            if idx < 0 or idx >= self.n_joints:
                continue

            # Left muscles produce positive torque (bend left)
            # Right muscles produce negative torque (bend right)
            sign = 1.0 if side == "left" else -1.0
            clamped = max(-1.0, min(1.0, activation))
            joint_torques[idx] += sign * clamped * MUSCLE_TORQUE_SCALE * motor_gain

        # Joint dynamics: torque - stiffness - damping
        # Moment of inertia for a segment: (1/12) * m * L^2
        moment_of_inertia = self._seg_mass * self._seg_length ** 2 / 12.0
        # Ensure minimum moment to prevent division instability
        moment_of_inertia = max(moment_of_inertia, 1e-6)

        angular_accel = (
            joint_torques
            - JOINT_STIFFNESS * self.segment_angles
            - JOINT_DAMPING * self.segment_angular_vel
        ) / moment_of_inertia

        # Clamp angular acceleration to prevent instability
        np.clip(angular_accel, -1000.0, 1000.0, out=angular_accel)

        # Integrate joint angles (semi-implicit Euler)
        self.segment_angular_vel += angular_accel * dt
        # Clamp angular velocity
        np.clip(self.segment_angular_vel, -50.0, 50.0, out=self.segment_angular_vel)
        self.segment_angles += self.segment_angular_vel * dt

        # Clamp joint angles and zero-out velocity at limits
        for j in range(self.n_joints):
            if self.segment_angles[j] > JOINT_RANGE:
                self.segment_angles[j] = JOINT_RANGE
                self.segment_angular_vel[j] = min(self.segment_angular_vel[j], 0.0)
            elif self.segment_angles[j] < -JOINT_RANGE:
                self.segment_angles[j] = -JOINT_RANGE
                self.segment_angular_vel[j] = max(self.segment_angular_vel[j], 0.0)

        # Compute thrust from body undulation (resistive force theory)
        # Each segment moving laterally through water generates a reaction force
        thrust_x = 0.0
        thrust_y = 0.0
        torque_body = 0.0

        angle = self.heading
        for i in range(self.n_segments):
            # Segment orientation
            if i < self.n_joints:
                seg_angle = angle + self.segment_angles[i] / 2
            else:
                seg_angle = angle

            # Tangent and normal unit vectors
            tx = math.cos(seg_angle)
            ty = math.sin(seg_angle)
            nx = -ty
            ny = tx

            # Segment velocity (relative to water, approximate)
            # Lateral velocity from angular change
            if i < self.n_joints:
                v_lateral = self.segment_angular_vel[i] * self._seg_length
            else:
                v_lateral = 0.0

            # Thrust from lateral motion (RFT: normal drag >> tangential drag)
            # Net force is in the tangent direction due to asymmetric drag
            f_normal = -C_NORMAL * v_lateral
            f_tangent = C_TANGENTIAL * v_lateral * 0.1  # small tangential component

            # Project forces into world frame
            thrust_x += f_normal * nx + f_tangent * tx
            thrust_y += f_normal * ny + f_tangent * ty

            # Accumulate angle for next segment
            if i < self.n_joints:
                angle += self.segment_angles[i]

        # Apply external forces
        for seg_name, force in self._external_forces.items():
            thrust_x += force[0]
            thrust_y += force[1]
            # force[2] ignored in 2D

        # Body drag (on COM motion)
        # Linear drag proportional to velocity
        drag_x = -C_TANGENTIAL * self.velocity[0]
        drag_y = -C_TANGENTIAL * self.velocity[1]

        # Integrate COM motion
        accel_x = (thrust_x + drag_x) / BODY_MASS
        accel_y = (thrust_y + drag_y) / BODY_MASS

        self.velocity[0] += accel_x * dt
        self.velocity[1] += accel_y * dt
        self.position[0] += self.velocity[0] * dt
        self.position[1] += self.velocity[1] * dt

        # Heading follows the average anterior body direction
        if self.n_joints > 0:
            # Heading change from anterior joint angles
            head_angle_change = np.mean(self.segment_angles[:min(3, self.n_joints)])
            self.heading += head_angle_change * dt * 10  # scale for responsiveness

        # Clear external forces
        self._external_forces.clear()

        return self.get_state()

    def apply_external_force(
        self, segment: str, force: tuple[float, float, float]
    ) -> None:
        """Apply external force to a segment on next step.

        Simulates a water current, touch stimulus, or perturbation.
        """
        self._external_forces[segment] = force

    def get_state(self) -> BodyState:
        """Return current body state."""
        seg_positions = self._compute_segment_positions()

        # Convert 2D positions to 3D (z=0 for fish swimming in a plane)
        positions_3d = [(x, y, 0.0) for x, y in seg_positions]
        # Identity quaternions (no 3D rotation)
        orientations = [(1.0, 0.0, 0.0, 0.0)] * self.n_segments

        joint_angles = list(self.segment_angles)
        contacts = [0.0] * self.n_segments  # no contact in water

        com_x = float(self.position[0])
        com_y = float(self.position[1])

        return BodyState(
            positions=positions_3d,
            orientations=orientations,
            joint_angles=joint_angles,
            contacts=contacts,
            center_of_mass=(com_x, com_y, 0.0),
        )

    @property
    def sensor_neuron_map(self) -> dict[str, str]:
        """Map sensor names to neuron IDs.

        Lateral line sensors map to auditory neurons in the
        Mauthner circuit.
        """
        mapping = {}
        for i in range(min(10, self.n_segments)):
            mapping[f"seg_{i}"] = f"AUD_{i}"
        return mapping

    @property
    def motor_neuron_map(self) -> dict[str, list[str]]:
        """Map motor neuron IDs to actuator names.

        Motor neurons MN_L_i / MN_R_i map to left/right muscles.
        """
        mapping: dict[str, list[str]] = {}

        for side, actuator_side in [("L", "left"), ("R", "right")]:
            for i in range(8):
                nid = f"MN_{side}_{i}"
                # Each motor neuron drives multiple adjacent segments
                # (motor unit spans ~2-3 segments)
                actuators = []
                # Map 8 motor neurons across n_joints joints
                seg_start = int(i * self.n_joints / 8)
                seg_end = int((i + 1) * self.n_joints / 8)
                for j in range(seg_start, min(seg_end + 1, self.n_joints)):
                    actuators.append(f"{actuator_side}_{j}")
                if actuators:
                    mapping[nid] = actuators

        return mapping

    @staticmethod
    def default_coupling_gains() -> dict:
        """Recommended CouplingConfig values for FishBody."""
        return {
            "firing_rate_to_torque_gain": 0.002,
            "inhibitory_gain": -0.001,
            "sensor_to_current_gain": 15.0,
            "sync_interval_ms": 1.0,
        }
