import { useCallback, useMemo, useState } from 'react';
import { useEvolutionStore } from '../../stores/evolutionStore';
import { useEvolution } from '../../hooks/useEvolution';
import { FitnessGraph } from './FitnessGraph';
import type { GodReport } from '../../types/evolution';

export function EvolutionDashboard() {
  const currentRun = useEvolutionStore((s) => s.currentRun);
  const fitnessHistory = useEvolutionStore((s) => s.fitnessHistory);
  const latestStats = useEvolutionStore((s) => s.latestStats);
  const godReports = useEvolutionStore((s) => s.godReports);
  const { start, pause, resume, backendAvailable } = useEvolution();

  // Derive God Agent display state from store reports + run data
  const godState = useMemo(() => {
    // Combine reports from the store and from the run object
    const runReports: GodReport[] = currentRun?.god_reports ?? [];
    const allReports = godReports.length > 0 ? godReports : runReports;

    if (allReports.length === 0) {
      return { active: false, mode: 'fallback', interventionCount: 0, latestAnalysis: '', interventions: [] as GodReport['interventions'] };
    }

    const totalInterventions = allReports.reduce(
      (sum, r) => sum + (r.interventions?.length ?? 0), 0
    );

    // Latest report with an analysis
    const latestWithAnalysis = [...allReports].reverse().find((r) => r.analysis);
    const latestAnalysis = latestWithAnalysis?.analysis ?? '';

    // Collect last 5 interventions across all reports
    const allInterventions: GodReport['interventions'] = [];
    for (const r of allReports) {
      if (r.interventions) {
        allInterventions.push(...r.interventions);
      }
    }

    // Get mode from the latest report that has it
    const mode = [...allReports].reverse().find((r) => r.mode)?.mode ?? 'fallback';

    return {
      active: true,
      mode,
      interventionCount: totalInterventions,
      latestAnalysis,
      interventions: allInterventions.slice(-5),
    };
  }, [godReports, currentRun]);

  const status = currentRun?.status ?? 'idle';
  const generation = currentRun?.generation ?? 0;
  const nGenerations = currentRun?.n_generations ?? 100;

  const [exporting, setExporting] = useState(false);

  const handleExportReport = useCallback(async () => {
    setExporting(true);
    try {
      let reportContent: string;

      if (backendAvailable && currentRun && !currentRun.id.startsWith('mock_')) {
        // Live mode: fetch report from API
        const res = await fetch(`/api/export/evolution/${currentRun.id}/report`);
        if (!res.ok) throw new Error(`API error ${res.status}`);
        reportContent = await res.text();
      } else {
        // Demo mode: fetch sample report from API, or generate locally
        try {
          const res = await fetch('/api/export/demo/report');
          if (res.ok) {
            reportContent = await res.text();
          } else {
            throw new Error('Demo endpoint unavailable');
          }
        } catch {
          // Generate a minimal report client-side from store data
          const history = useEvolutionStore.getState().fitnessHistory;
          const run = useEvolutionStore.getState().currentRun;
          const gen = run?.generation ?? 0;
          const best = run?.best_fitness ?? 0;
          const mean = run?.mean_fitness ?? 0;

          reportContent = [
            '# Neurevo Scientific Report',
            `## Demo Run | *C. elegans* | ${gen} Generations`,
            '',
            '---',
            '',
            '## 1. Overview',
            '',
            '| Parameter | Value |',
            '|-----------|-------|',
            `| Run ID | \`${run?.id ?? 'demo'}\` |`,
            '| Organism | C. elegans |',
            `| Generations | ${gen} |`,
            `| Population size | ${run?.population_size ?? 150} |`,
            '',
            '## 2. Fitness Trajectory',
            '',
            '| Metric | Value |',
            '|--------|------:|',
            `| Final best fitness | ${best.toFixed(4)} |`,
            `| Final mean fitness | ${mean.toFixed(4)} |`,
            '',
            '### Per-Generation Data',
            '',
            '| Generation | Best | Mean |',
            '|:----------:|-----:|-----:|',
            ...history.generations.map((g, i) =>
              `| ${g} | ${history.best[i]?.toFixed(4) ?? 'N/A'} | ${history.mean[i]?.toFixed(4) ?? 'N/A'} |`
            ),
            '',
            '---',
            '',
            '## Methods',
            '',
            'This report was generated from client-side demo data.',
            'For a full report with connectome drift analysis, behavioral',
            'analysis, and God Agent intervention summaries, run evolution',
            'with the backend API connected.',
            '',
            '---',
            '',
            '*Report generated by Neurevo (demo mode)*',
          ].join('\n');
        }
      }

      // Download as .md file
      const blob = new Blob([reportContent], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `neurevo_report_${currentRun?.id ?? 'demo'}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Failed to export report:', err);
    } finally {
      setExporting(false);
    }
  }, [backendAvailable, currentRun]);

  return (
    <>
      {/* Backend status banner — only shown when using mock data */}
      {backendAvailable === false && status !== 'idle' && (
        <div className="glass" style={{ padding: '6px 10px', fontSize: 10, color: 'var(--accent-amber)', textAlign: 'center' }}>
          No backend — running local simulation
        </div>
      )}

      {/* Generation counter */}
      <div className="glass">
        <div className="glass-label">Evolution</div>
        <div className="evo-generation-counter">{generation}</div>
        <div style={{ fontSize: 10, color: 'var(--text-label)', textAlign: 'center', marginTop: 2 }}>
          of {nGenerations} generations
        </div>
        <div style={{
          marginTop: 8,
          height: 3,
          borderRadius: 2,
          background: 'rgba(255,255,255,0.04)',
          overflow: 'hidden',
        }}>
          <div style={{
            width: `${(generation / nGenerations) * 100}%`,
            height: '100%',
            background: 'linear-gradient(90deg, var(--accent-cyan), var(--accent-green))',
            borderRadius: 2,
            transition: 'width 0.3s ease',
          }} />
        </div>
      </div>

      {/* Fitness stats */}
      <div className="glass">
        <div className="glass-label">Fitness</div>
        <div className="stat-row">
          <span className="stat-label">Best</span>
          <span className="stat-value stat-cyan">{(currentRun?.best_fitness ?? 0).toFixed(3)}</span>
        </div>
        <div className="stat-row">
          <span className="stat-label">Mean</span>
          <span className="stat-value stat-green">{(currentRun?.mean_fitness ?? 0).toFixed(3)}</span>
        </div>
        <div className="stat-row">
          <span className="stat-label">Std dev</span>
          <span className="stat-value" style={{ color: 'var(--text-secondary)', fontSize: 13 }}>
            {(latestStats?.std_fitness ?? 0).toFixed(3)}
          </span>
        </div>
      </div>

      {/* Population info */}
      <div className="glass">
        <div className="glass-label">Population</div>
        <div className="stat-row">
          <span className="stat-label">Size</span>
          <span className="stat-value stat-amber">{currentRun?.population_size ?? 150}</span>
        </div>
        <div className="stat-row">
          <span className="stat-label">Species</span>
          <span className="stat-value stat-magenta">{latestStats?.n_species ?? 0}</span>
        </div>
        <div className="stat-row">
          <span className="stat-label">Status</span>
          <span className="stat-value" style={{
            fontSize: 11,
            color: status === 'running' ? 'var(--accent-green)'
              : status === 'paused' ? 'var(--accent-amber)'
              : status === 'completed' ? 'var(--accent-cyan)'
              : 'var(--text-label)',
          }}>
            {status.toUpperCase()}
          </span>
        </div>
      </div>

      {/* Controls */}
      <div className="glass">
        <div className="glass-label">Controls</div>
        <div style={{ display: 'flex', gap: 6 }}>
          {status === 'idle' || status === 'completed' ? (
            <button className="btn btn-primary" style={{ flex: 1 }} onClick={() => start()}>
              {status === 'completed' ? 'Restart' : 'Start Evolution'}
            </button>
          ) : status === 'running' ? (
            <button className="btn btn-amber" style={{ flex: 1 }} onClick={pause}>
              Pause
            </button>
          ) : (
            <>
              <button className="btn btn-primary" style={{ flex: 1 }} onClick={resume}>
                Resume
              </button>
              <button className="btn btn-ghost" style={{ flex: 1 }} onClick={() => start()}>
                Restart
              </button>
            </>
          )}
        </div>
      </div>

      {/* Export */}
      {(status === 'completed' || status === 'paused' || generation > 0) && (
        <div className="glass">
          <div className="glass-label">Export</div>
          <button
            className="btn btn-ghost"
            style={{ width: '100%', fontSize: 11 }}
            onClick={handleExportReport}
            disabled={exporting}
          >
            {exporting ? 'Generating...' : 'Export Report (.md)'}
          </button>
        </div>
      )}

      {/* Mini fitness graph */}
      <div className="glass" style={{ padding: 8 }}>
        <div className="glass-label">Fitness Curve</div>
        <FitnessGraph history={fitnessHistory} width={196} height={120} />
      </div>

      {/* God Agent section */}
      {godState.active && (
        <div className="glass" style={{ position: 'relative' }}>
          <div className="glass-label" style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
            <span
              style={{
                display: 'inline-block',
                width: 8,
                height: 8,
                borderRadius: '50%',
                background: status === 'running' ? 'var(--accent-magenta)' : 'var(--text-label)',
                boxShadow: status === 'running' ? '0 0 6px var(--accent-magenta)' : 'none',
                animation: status === 'running' ? 'god-pulse 2s ease-in-out infinite' : 'none',
              }}
            />
            God Agent
            <span style={{ fontSize: 9, color: 'var(--text-label)', marginLeft: 'auto' }}>
              {godState.mode.toUpperCase()}
            </span>
          </div>
          <div className="stat-row">
            <span className="stat-label">Interventions</span>
            <span className="stat-value stat-magenta">{godState.interventionCount}</span>
          </div>
          {godState.latestAnalysis && (
            <div style={{
              marginTop: 6,
              padding: '4px 6px',
              fontSize: 9,
              lineHeight: 1.4,
              color: 'var(--text-secondary)',
              background: 'rgba(255,255,255,0.02)',
              borderRadius: 4,
              fontFamily: 'monospace',
              wordBreak: 'break-word',
            }}>
              {godState.latestAnalysis}
            </div>
          )}
          {godState.interventions.length > 0 && (
            <div style={{ marginTop: 6 }}>
              {godState.interventions.map((iv, i) => (
                <div
                  key={i}
                  style={{
                    padding: '3px 6px',
                    marginTop: 3,
                    fontSize: 9,
                    lineHeight: 1.3,
                    color: 'var(--accent-amber)',
                    background: 'rgba(255,180,50,0.06)',
                    borderRadius: 3,
                    borderLeft: '2px solid var(--accent-amber)',
                  }}
                >
                  <strong>{iv.action}</strong>: {iv.description}
                </div>
              ))}
            </div>
          )}
          <style>{`
            @keyframes god-pulse {
              0%, 100% { opacity: 0.4; transform: scale(1); }
              50% { opacity: 1; transform: scale(1.3); }
            }
          `}</style>
        </div>
      )}
    </>
  );
}
