"""Consciousness metrics for spiking neural networks.

Implements four complementary measures of neural consciousness/awareness:

1. **Integrated Information (Φ)** — Tononi's IIT: how much more information
   the whole system generates than the sum of its parts.
2. **Global Workspace Ignition** — Dehaene/Changeux: detection of sudden
   broadcast events where local activity propagates globally.
3. **Neural Complexity (CN)** — Tononi-Sporns-Edelman: integration of
   mutual information across multiple spatial scales.
4. **Perturbational Complexity Index (PCI)** — Casali et al.: compress
   the network's response to perturbation via Lempel-Ziv.

All metrics operate on spike trains (indices + times) and optionally
on connectome structure for graph-based measures.

References:
    - Tononi (2004) "An information integration theory of consciousness"
    - Dehaene & Changeux (2011) "Experimental and theoretical approaches
      to conscious processing"
    - Tononi, Sporns & Edelman (1994) "A measure for brain complexity"
    - Casali et al. (2013) "A theoretically based index of consciousness"
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)


# ======================================================================
# Shared helpers
# ======================================================================

def _build_spike_matrix(
    spike_indices: np.ndarray,
    spike_times_ms: np.ndarray,
    neuron_ids: np.ndarray,
    n_bins: int,
    bin_ms: float,
) -> np.ndarray:
    """Build a binary (n_bins, n_neurons) spike matrix from raw spike data.

    Args:
        spike_indices: Neuron index for each spike.
        spike_times_ms: Time (ms) for each spike.
        neuron_ids: Array of neuron IDs to include (column order).
        n_bins: Number of time bins.
        bin_ms: Width of each time bin in ms.

    Returns:
        Binary float32 matrix of shape (n_bins, len(neuron_ids)).
    """
    mat = np.zeros((n_bins, len(neuron_ids)), dtype=np.float32)
    remap = {nid: i for i, nid in enumerate(neuron_ids)}
    for idx, t in zip(spike_indices, spike_times_ms):
        if idx in remap:
            b = min(int(t / bin_ms), n_bins - 1)
            mat[b, remap[idx]] = 1.0
    return mat


# ======================================================================
# Data structures
# ======================================================================

@dataclass
class ConsciousnessReport:
    """Unified report from all consciousness metrics."""
    phi: float = 0.0
    phi_partition: dict[str, Any] = field(default_factory=dict)
    ignition_events: list[dict] = field(default_factory=list)
    ignition_rate: float = 0.0
    neural_complexity: float = 0.0
    complexity_profile: list[float] = field(default_factory=list)
    pci: float = 0.0
    pci_details: dict[str, Any] = field(default_factory=dict)

    def summary(self) -> str:
        return (
            f"Φ={self.phi:.4f} | Ignitions={len(self.ignition_events)} "
            f"({self.ignition_rate:.1f}/s) | CN={self.neural_complexity:.4f} | "
            f"PCI={self.pci:.4f}"
        )


# ======================================================================
# 1. Integrated Information (Φ) — IIT
# ======================================================================

def compute_phi(
    spike_indices: np.ndarray,
    spike_times_ms: np.ndarray,
    n_neurons: int,
    duration_ms: float,
    bin_ms: float = 10.0,
    top_k: int | None = None,
    n_partitions: int = 50,
    seed: int = 42,
) -> dict[str, Any]:
    """Compute Integrated Information (Φ) via greedy partition search.

    Φ measures how much information is generated by the whole system
    above and beyond what is generated by its parts independently.

    Φ = MI(past → future | whole) - max_partition Σ MI(past → future | part_i)

    Since exact Φ is exponential in neuron count, we use:
    1. Select top-k most active neurons
    2. Bin spikes into discrete time windows
    3. Compute time-lagged mutual information for the whole system
    4. Search partitions greedily to find the minimum information partition
    5. Φ = whole MI - partitioned MI

    Args:
        spike_indices: Neuron index for each spike.
        spike_times_ms: Time (ms) for each spike.
        n_neurons: Total neuron count.
        duration_ms: Total recording duration.
        bin_ms: Time bin width for discretization.
        top_k: Number of most active neurons to analyze. If None, scales
            adaptively with network size: min(max(30, int(sqrt(n)*2)), 100).
        n_partitions: Number of random partitions to try.
        seed: Random seed.

    Returns:
        Dictionary with phi, partition info, and per-neuron contributions.
    """
    # Adaptive top_k: scale with network size for better coverage
    if top_k is None:
        top_k = min(max(30, int(np.sqrt(n_neurons) * 2)), 100)
    if len(spike_indices) == 0:
        return {"phi": 0.0, "partition": {}, "n_analyzed": 0}

    rng = np.random.default_rng(seed)
    spike_indices = np.asarray(spike_indices)
    spike_times_ms = np.asarray(spike_times_ms)

    # Select neurons with diverse firing patterns (not just the most active)
    unique, counts = np.unique(spike_indices, return_counts=True)

    # Filter to neurons with enough spikes to be informative
    min_spikes = max(3, int(duration_ms / bin_ms * 0.05))
    active_mask = counts >= min_spikes
    active_neurons = unique[active_mask]
    active_counts = counts[active_mask]

    if len(active_neurons) < 4:
        return {"phi": 0.0, "partition": {}, "n_analyzed": len(active_neurons)}

    # Build spike matrix for ALL active neurons first, then select diverse ones
    n_bins = max(int(duration_ms / bin_ms), 2)
    candidate_k = min(len(active_neurons), top_k * 10)
    # Take a spread of activity levels: top, middle, lower
    if len(active_neurons) > candidate_k:
        sorted_idx = np.argsort(-active_counts)
        # Sample from top third, middle third, bottom third
        third = candidate_k // 3
        top_neurons = sorted_idx[:third]
        mid_start = len(sorted_idx) // 3
        mid_neurons = sorted_idx[mid_start:mid_start + third]
        low_start = 2 * len(sorted_idx) // 3
        low_neurons = sorted_idx[low_start:low_start + (candidate_k - 2 * third)]
        candidate_idx = np.concatenate([top_neurons, mid_neurons, low_neurons])
        candidates = active_neurons[candidate_idx]
    else:
        candidates = active_neurons

    # Build spike matrix for candidates
    spike_mat_full = _build_spike_matrix(
        spike_indices, spike_times_ms, candidates, n_bins, bin_ms,
    )

    # Select top_k neurons with most diverse patterns (highest entropy)
    entropies = np.zeros(len(candidates))
    for j in range(len(candidates)):
        col = spike_mat_full[:, j]
        p = col.mean()
        if 0 < p < 1:
            entropies[j] = -p * np.log2(p) - (1 - p) * np.log2(1 - p)

    # Pick neurons with highest individual entropy (most variable firing)
    if len(candidates) > top_k:
        diverse_idx = np.argsort(-entropies)[:top_k]
    else:
        diverse_idx = np.arange(len(candidates))
        top_k = len(candidates)

    selected = candidates[diverse_idx]
    spike_matrix = spike_mat_full[:, diverse_idx]

    # Use Gaussian approximation of MI via covariance (practical IIT)
    # This captures temporal correlations due to synaptic connections.
    # MI_gauss = 0.5 * log(det(cov_past) * det(cov_future) / det(cov_joint))

    past = spike_matrix[:-1]  # (n_bins-1, k)
    future = spike_matrix[1:]  # (n_bins-1, k)

    whole_mi = _gaussian_mi(past, future)

    # Greedy partition search for minimum information partition
    best_partition_mi = whole_mi
    best_partition = None

    for _ in range(n_partitions):
        perm = rng.permutation(top_k)
        split = max(2, rng.integers(top_k // 4, 3 * top_k // 4 + 1))
        part_a = perm[:split]
        part_b = perm[split:]

        mi_a = _gaussian_mi(past[:, part_a], future[:, part_a])
        mi_b = _gaussian_mi(past[:, part_b], future[:, part_b])
        partition_mi = mi_a + mi_b

        if partition_mi < best_partition_mi:
            best_partition_mi = partition_mi
            best_partition = {
                "a": part_a.tolist(),
                "b": part_b.tolist(),
                "mi_a": float(mi_a),
                "mi_b": float(mi_b),
            }

    phi = max(0.0, whole_mi - best_partition_mi)

    return {
        "phi": float(phi),
        "whole_mi": float(whole_mi),
        "partition_mi": float(best_partition_mi),
        "partition": best_partition or {},
        "n_analyzed": top_k,
        "selected_neurons": selected.tolist(),
    }


def _gaussian_mi(x: np.ndarray, y: np.ndarray) -> float:
    """Compute mutual information under Gaussian approximation.

    MI_gauss = 0.5 * [log det(Σ_x) + log det(Σ_y) - log det(Σ_xy)]

    This is the standard practical approximation for IIT and captures
    temporal correlations between neural populations.
    """
    n_samples, n_x = x.shape
    _, n_y = y.shape
    if n_samples < 10 or n_x == 0 or n_y == 0:
        return 0.0

    # Add small regularization to prevent singular covariance
    eps = 1e-6

    # Covariance of x
    cov_x = np.cov(x.T) + eps * np.eye(n_x)
    # Covariance of y
    cov_y = np.cov(y.T) + eps * np.eye(n_y)
    # Joint covariance
    xy = np.hstack([x, y])
    cov_xy = np.cov(xy.T) + eps * np.eye(n_x + n_y)

    # Handle scalar covariance (1 neuron)
    if n_x == 1:
        cov_x = cov_x.reshape(1, 1)
    if n_y == 1:
        cov_y = cov_y.reshape(1, 1)

    # log det via slogdet for numerical stability
    _, logdet_x = np.linalg.slogdet(cov_x)
    _, logdet_y = np.linalg.slogdet(cov_y)
    _, logdet_xy = np.linalg.slogdet(cov_xy)

    mi = 0.5 * (logdet_x + logdet_y - logdet_xy)
    return max(0.0, float(mi))


def _time_lagged_mi(past: np.ndarray, future: np.ndarray, n_bins: int = 8) -> float:
    """Compute time-lagged mutual information between past and future states.

    Discretizes the multi-dimensional state by hashing binary patterns
    into integer labels, then computes standard MI.

    I(past; future) = H(past) + H(future) - H(past, future)
    """
    n_samples, n_vars = past.shape
    if n_samples < 10 or n_vars == 0:
        return 0.0

    # Hash each timestep's binary pattern into an integer label
    # For efficiency, use dot product with powers of 2
    if n_vars <= 20:
        powers = 2 ** np.arange(n_vars)
        past_labels = past.astype(int) @ powers
        future_labels = future.astype(int) @ powers
    else:
        # For larger systems, use coarser discretization
        # Sum active neurons in groups of 5
        group_size = 5
        n_groups = (n_vars + group_size - 1) // group_size
        past_grouped = np.zeros((n_samples, n_groups), dtype=int)
        future_grouped = np.zeros((n_samples, n_groups), dtype=int)
        for g in range(n_groups):
            s = g * group_size
            e = min(s + group_size, n_vars)
            past_grouped[:, g] = np.clip(past[:, s:e].sum(axis=1), 0, n_bins - 1).astype(int)
            future_grouped[:, g] = np.clip(future[:, s:e].sum(axis=1), 0, n_bins - 1).astype(int)
        powers = n_bins ** np.arange(n_groups)
        past_labels = past_grouped @ powers
        future_labels = future_grouped @ powers

    return _mi_from_labels(past_labels, future_labels)


def _mi_from_labels(x: np.ndarray, y: np.ndarray) -> float:
    """Mutual information between two integer label arrays."""
    n = len(x)
    if n < 2:
        return 0.0

    # Joint histogram via numpy
    xy = np.stack([x, y], axis=1)
    # Use structured array for unique counting
    xy_tuples = np.ascontiguousarray(xy).view(
        np.dtype((np.void, xy.dtype.itemsize * xy.shape[1]))
    )
    _, joint_counts = np.unique(xy_tuples, return_counts=True)
    _, x_counts = np.unique(x, return_counts=True)
    _, y_counts = np.unique(y, return_counts=True)

    # Entropy computation
    def entropy(counts):
        p = counts / counts.sum()
        p = p[p > 0]
        return -np.sum(p * np.log2(p))

    h_x = entropy(x_counts)
    h_y = entropy(y_counts)
    h_xy = entropy(joint_counts)

    return max(0.0, h_x + h_y - h_xy)


# ======================================================================
# 2. Global Workspace Ignition Detection
# ======================================================================

def detect_ignition_events(
    spike_indices: np.ndarray,
    spike_times_ms: np.ndarray,
    n_neurons: int,
    activation_threshold: float = 0.10,
    window_ms: float = 50.0,
    min_gap_ms: float = 100.0,
    baseline_rate: float | None = None,
) -> list[dict[str, Any]]:
    """Detect Global Workspace-style ignition events.

    An "ignition" occurs when neural activity suddenly transitions from
    sparse/local to widespread/global activation. This is detected as a
    rapid increase in the fraction of active neurons within a time window.

    Args:
        spike_indices: Neuron index for each spike.
        spike_times_ms: Time (ms) for each spike.
        n_neurons: Total neuron count.
        activation_threshold: Fraction of neurons that must be active
            for an ignition (default 10%).
        window_ms: Time window for measuring activation spread.
        min_gap_ms: Minimum gap between ignition events.
        baseline_rate: Expected baseline activation rate. If None,
            computed from data.

    Returns:
        List of ignition event dicts with time, strength, participants.
    """
    if len(spike_indices) == 0 or n_neurons == 0:
        return []

    spike_indices = np.asarray(spike_indices)
    spike_times_ms = np.asarray(spike_times_ms)

    t_min = spike_times_ms.min()
    t_max = spike_times_ms.max()
    if t_max - t_min < window_ms:
        return []

    # Slide window across time
    step_ms = window_ms / 2  # 50% overlap
    window_starts = np.arange(t_min, t_max - window_ms, step_ms)

    # Compute activation fraction for each window
    activations = np.zeros(len(window_starts))
    for i, t_start in enumerate(window_starts):
        mask = (spike_times_ms >= t_start) & (spike_times_ms < t_start + window_ms)
        n_active = len(np.unique(spike_indices[mask]))
        activations[i] = n_active / n_neurons

    if baseline_rate is None:
        baseline_rate = np.median(activations)

    # Detect threshold crossings (activation above threshold AND above baseline)
    threshold = max(activation_threshold, baseline_rate * 3.0)
    above = activations >= threshold

    # Find onset of each ignition event (transition from below to above)
    events = []
    last_event_time = -min_gap_ms * 2

    for i in range(1, len(above)):
        if above[i] and not above[i - 1]:
            event_time = window_starts[i]
            if event_time - last_event_time < min_gap_ms:
                continue

            # Find peak activation within this event
            peak_idx = i
            j = i + 1
            while j < len(above) and above[j]:
                if activations[j] > activations[peak_idx]:
                    peak_idx = j
                j += 1

            # Get participating neurons
            peak_start = window_starts[peak_idx]
            mask = (spike_times_ms >= peak_start) & (
                spike_times_ms < peak_start + window_ms
            )
            participants = np.unique(spike_indices[mask])

            events.append({
                "time_ms": float(event_time),
                "peak_time_ms": float(window_starts[peak_idx]),
                "peak_activation": float(activations[peak_idx]),
                "n_participating": int(len(participants)),
                "fraction_participating": float(len(participants) / n_neurons),
                "duration_ms": float((j - i) * step_ms),
                "strength": float(activations[peak_idx] / max(baseline_rate, 1e-6)),
            })
            last_event_time = event_time

    return events


# ======================================================================
# 3. Neural Complexity (Tononi-Sporns-Edelman)
# ======================================================================

def compute_neural_complexity(
    spike_indices: np.ndarray,
    spike_times_ms: np.ndarray,
    n_neurons: int,
    duration_ms: float,
    bin_ms: float = 10.0,
    max_scale: int = 10,
    top_k: int | None = None,
    n_samples_per_scale: int = 20,
    seed: int = 42,
) -> dict[str, Any]:
    """Compute Neural Complexity (CN) across spatial scales.

    CN measures the degree to which a neural system simultaneously shows
    functional specialization (different parts do different things) and
    functional integration (parts coordinate).

    CN = Σ_k [MI(subset_k; rest) averaged over random subsets of size k]

    High CN indicates a system between two extremes:
    - Fully random (no integration → low CN)
    - Fully synchronized (no specialization → low CN)

    Args:
        spike_indices, spike_times_ms: Spike data.
        n_neurons: Total neuron count.
        duration_ms: Recording duration.
        bin_ms: Discretization bin width.
        max_scale: Maximum subset size to test.
        top_k: Number of most active neurons to analyze.
        n_samples_per_scale: Random subsets per scale.
        seed: Random seed.

    Returns:
        Dictionary with complexity score and scale profile.
    """
    if len(spike_indices) == 0:
        return {"complexity": 0.0, "profile": [], "n_analyzed": 0}

    # Adaptive top_k: scale with network size
    if top_k is None:
        top_k = min(max(60, int(np.sqrt(n_neurons) * 3)), 150)

    rng = np.random.default_rng(seed)
    spike_indices = np.asarray(spike_indices)
    spike_times_ms = np.asarray(spike_times_ms)

    # Select most active neurons
    unique, counts = np.unique(spike_indices, return_counts=True)
    if len(unique) > top_k:
        selected = unique[np.argsort(-counts)[:top_k]]
    else:
        selected = unique
        top_k = len(selected)

    if top_k < 4:
        return {"complexity": 0.0, "profile": [], "n_analyzed": top_k}

    # Build binary spike matrix
    n_bins = max(int(duration_ms / bin_ms), 2)
    spike_matrix = _build_spike_matrix(
        spike_indices, spike_times_ms, selected, n_bins, bin_ms,
    )

    max_scale = min(max_scale, top_k // 2)
    profile = []

    for k in range(1, max_scale + 1):
        mi_values = []
        for _ in range(n_samples_per_scale):
            subset = rng.choice(top_k, size=k, replace=False)
            rest = np.setdiff1d(np.arange(top_k), subset)
            if len(rest) == 0:
                continue

            # Compute MI between subset and rest
            sub_data = spike_matrix[:, subset]
            rest_data = spike_matrix[:, rest]

            # Hash each to labels
            if k <= 20:
                sub_labels = sub_data.astype(int) @ (2 ** np.arange(k))
            else:
                sub_labels = sub_data.sum(axis=1).astype(int)

            rest_k = min(len(rest), 20)
            if rest_k <= 20:
                rest_labels = rest_data[:, :rest_k].astype(int) @ (2 ** np.arange(rest_k))
            else:
                rest_labels = rest_data.sum(axis=1).astype(int)

            mi = _mi_from_labels(sub_labels, rest_labels)
            mi_values.append(mi)

        avg_mi = float(np.mean(mi_values)) if mi_values else 0.0
        profile.append(avg_mi)

    complexity = float(np.sum(profile))

    return {
        "complexity": complexity,
        "profile": profile,
        "max_scale": max_scale,
        "n_analyzed": top_k,
    }


# ======================================================================
# 4. Perturbational Complexity Index (PCI)
# ======================================================================

def compute_pci(
    response_matrix: np.ndarray,
    threshold: float | None = None,
) -> dict[str, Any]:
    """Compute Perturbational Complexity Index from an evoked response.

    PCI = LZ(response) / H(response)

    where LZ is the Lempel-Ziv complexity of the binarized spatiotemporal
    response matrix, and H is its source entropy.

    Higher PCI indicates more complex (conscious-like) processing:
    - Simple propagation (chain) → low PCI
    - No propagation (disconnected) → low PCI
    - Rich, differentiated propagation → high PCI

    Args:
        response_matrix: Binary (n_time, n_neurons) evoked response matrix.
            1 = neuron fired in this time bin, 0 = silent.
        threshold: Binarization threshold (default: auto from data).

    Returns:
        Dictionary with PCI score and component metrics.
    """
    mat = np.asarray(response_matrix, dtype=np.float32)
    if mat.size == 0:
        return {"pci": 0.0, "lz_complexity": 0, "source_entropy": 0.0}

    n_time, n_neurons = mat.shape

    # Binarize — use the matrix values directly if already binary (0/1),
    # otherwise threshold at the median of nonzero values
    if threshold is None:
        nonzero = mat[mat > 0]
        if len(nonzero) > 0:
            threshold = np.median(nonzero) * 0.5
        else:
            threshold = 0.5
    binary = (mat >= threshold).astype(np.uint8)

    # Flatten spatiotemporal matrix to 1D bit string (column-major for spatial spread)
    bit_string = binary.T.ravel()

    # Lempel-Ziv complexity
    lz = _lempel_ziv_complexity(bit_string)

    # Source entropy
    p1 = np.mean(binary)
    if p1 <= 0 or p1 >= 1:
        source_entropy = 0.0
    else:
        source_entropy = -p1 * np.log2(p1) - (1 - p1) * np.log2(1 - p1)

    # Normalised PCI
    n_total = n_time * n_neurons
    if source_entropy > 0 and n_total > 0:
        # Normalise by the expected LZ for a random binary string with same density
        expected_lz = n_total * source_entropy / np.log2(n_total + 1)
        pci = lz / max(expected_lz, 1e-6)
    else:
        pci = 0.0

    return {
        "pci": float(pci),
        "lz_complexity": int(lz),
        "source_entropy": float(source_entropy),
        "n_time": n_time,
        "n_neurons": n_neurons,
        "active_fraction": float(p1),
    }


def _lempel_ziv_complexity(s: np.ndarray) -> int:
    """Compute Lempel-Ziv complexity of a binary sequence (LZ76).

    Uses set-based substring lookup for O(n log n) average performance
    instead of O(n²k) brute-force scanning.
    """
    n = len(s)
    if n == 0:
        return 0

    # Convert to bytes for fast substring matching
    s_bytes = bytes(s.astype(np.uint8))
    seen: set[bytes] = set()
    complexity = 0
    i = 0

    while i < n:
        # Find the shortest substring starting at i not yet seen
        k = 1
        while i + k <= n:
            substr = s_bytes[i:i + k]
            if substr not in seen:
                seen.add(substr)
                complexity += 1
                i += k
                break
            k += 1
        else:
            # Reached end of string
            complexity += 1
            break

    return complexity


# ======================================================================
# Convenience: Run all metrics at once
# ======================================================================

def compute_all_consciousness_metrics(
    spike_indices: np.ndarray,
    spike_times_ms: np.ndarray,
    n_neurons: int,
    duration_ms: float,
    response_matrix: np.ndarray | None = None,
    bin_ms: float = 10.0,
    top_k: int | None = None,
    seed: int = 42,
) -> ConsciousnessReport:
    """Compute all four consciousness metrics.

    Args:
        spike_indices, spike_times_ms: Spike data from simulation.
        n_neurons: Total neuron count.
        duration_ms: Total recording duration.
        response_matrix: Optional evoked response matrix for PCI.
            If None, PCI is computed from the spike data directly.
        bin_ms: Time bin width for discretization.
        top_k: Number of neurons to analyze for Φ. If None, scales
            adaptively with network size.
        seed: Random seed.

    Returns:
        ConsciousnessReport with all metrics.
    """
    spike_indices = np.asarray(spike_indices)
    spike_times_ms = np.asarray(spike_times_ms)

    # Resolve adaptive top_k once for consistent usage across all metrics
    if top_k is None:
        top_k = min(max(30, int(np.sqrt(n_neurons) * 2)), 100)

    # 1. Integrated Information (Φ)
    phi_result = compute_phi(
        spike_indices, spike_times_ms, n_neurons, duration_ms,
        bin_ms=bin_ms, top_k=top_k, seed=seed,
    )

    # 2. Global Workspace Ignition
    ignition_events = detect_ignition_events(
        spike_indices, spike_times_ms, n_neurons,
    )
    ignition_rate = len(ignition_events) / max(duration_ms / 1000.0, 0.001)

    # 3. Neural Complexity
    complexity_result = compute_neural_complexity(
        spike_indices, spike_times_ms, n_neurons, duration_ms,
        bin_ms=bin_ms, top_k=min(top_k * 2, 60), seed=seed,
    )

    # 4. PCI
    if response_matrix is not None:
        pci_result = compute_pci(response_matrix)
    else:
        # Build response matrix from spikes
        n_bins = max(int(duration_ms / bin_ms), 2)
        n_k = min(n_neurons, 200)
        unique, counts = np.unique(spike_indices, return_counts=True)
        if len(unique) > n_k:
            selected = unique[np.argsort(-counts)[:n_k]]
        else:
            selected = unique
            n_k = len(selected)

        mat = _build_spike_matrix(
            spike_indices, spike_times_ms, selected, n_bins, bin_ms,
        )

        pci_result = compute_pci(mat)

    return ConsciousnessReport(
        phi=phi_result["phi"],
        phi_partition=phi_result,
        ignition_events=ignition_events,
        ignition_rate=ignition_rate,
        neural_complexity=complexity_result["complexity"],
        complexity_profile=complexity_result["profile"],
        pci=pci_result["pci"],
        pci_details=pci_result,
    )
